INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('ana@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');

    INSERT INTO tb_movie(score, count, title, image) VALUES (4.5, 2, ' Dragon Ball Z (1989) ', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/eg2CakFFQh3dvujVj2qYCe7ybvK.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (3.3, 3, 'Naruto: OVA', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/mpFZiRihCsPDdZ1Ef69WIengKh2.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, ' One Punch Man (2015) tro', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/a8BknzvFVK5EZ83rKg1a83iwaj0.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, ' One Piece (1999)', 'https://www.themoviedb.org/t/p/original/j99mTg35DiSk58wF7EC3rVxylDH.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, ' Hunter x Hunter (2011) ', 'https://www.themoviedb.org/t/p/original/tolQj5yffSxkEGXusPwNcvYrbph.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, ' Jujutsu Kaisen (2020) ', 'https://www.themoviedb.org/t/p/original/eGYaVtwWInTzAT6HOGyAj1BTqnB.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, ' Kimetsu no Yaiba (2019) ', 'https://www.themoviedb.org/t/p/original/7Uj6vqmznWQ3w3hpQ1eIY9mMyMw.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, ' Attack on Titan (2013) ', 'https://www.themoviedb.org/t/p/original/1XnZJZ6QDxgaVbnsGpNrBi13JfI.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, ' My Hero Academia: O Filme - 2 Heróis (2018) ', 'https://www.themoviedb.org/t/p/original/cF567qKeiEHZVxpVq4KFG8T7yLA.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Haikyuu!!', 'https://www.themoviedb.org/t/p/original/qNKaeunuUdL0smnowVVgShCkWZ4.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, ' Bleach: 4 - Jigoku-hen (2010) ', 'https://www.themoviedb.org/t/p/original/pd7V5iCB19VBPJkihxFXFwSRW2M.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Yu Yu Hakusho: Invasores do Inferno (1994)', 'https://www.themoviedb.org/t/p/original/oxE5zSdWgXYNlCMatZ6k0qwK7B3.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Fullmetal Alchemist, o Filme: O Conquistador de Shamballa', 'https://www.themoviedb.org/t/p/original/x5Y3XY9WF4gssfnyNWiCK2JcBoh.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, ' Os Cavaleiros do Zodíaco (1986) ', 'https://www.themoviedb.org/t/p/original/lGuI2iBUowwfG0pjJi7rEviZ5xs.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, ' Super Campeões (1983) ', 'https://www.themoviedb.org/t/p/original/lmlLOWx7lDZTSJ9iMVZmyRb3Y1h.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, ' Dragon Ball GT (1996) ', 'https://www.themoviedb.org/t/p/original/kmO4AHj1xx8wiaBMgwGjXhOQfNt.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, ' Yu-Gi-Oh! (2000) ', 'https://www.themoviedb.org/t/p/original/vDI0u6jomTQ0ZrVlrKyRJCgR3YW.jpg');

    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, ' Samurai X (1996) ', 'https://www.themoviedb.org/t/p/original/qYBFkIAlFCup6IqGXAvVwUHHwjG.jpg');
--     INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, ' JoJo' ,'s Bizarre Adventure (1993) ', 'https://www.themoviedb.org/t/p/original/thyLlWU5CyenrPxKunztZFwfZE1.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Os Sete Pecados Capitais (2014', 'https://www.themoviedb.org/t/p/original/fJ0Jy7NNdqIuYcYNqeK7YJHVLL0.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Mob Psycho 100 (2016)', 'https://www.themoviedb.org/t/p/original/aFcv9zeJtSbJHSYUlQCOQYV3Gio.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Baki', 'https://www.themoviedb.org/t/p/original/diySGgcj1xikHU7ACEugcvW88WQ.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Nausicaä do Vale do Vento (1984)', 'https://www.themoviedb.org/t/p/original/j9SCbf05YWwxCbCcXZyBsMkRagP.jpgjpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Fantasma do Futuro (1995)', 'https://www.themoviedb.org/t/p/original/4YgDy47HKxcSwUPQWrg0J39lEZA.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Último DueloCowboy Bebop - O Filme (2001)', 'https://www.themoviedb.org/t/p/original/cfDLndab6CKVgI1MpCbZM45c9gU.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, ' Akame ga Kill (2014) ', 'https://www.themoviedb.org/t/p/original/hDzm2VXxdeK5kztUN3RWTkBsBZg.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, ' Kiseijuu: Sei no Kakuritsu (2014) ', 'https://www.themoviedb.org/t/p/original/dC1rIfKScgrHjmZYdTpUgWpZF4h.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, ' Dragon Ball Absalon (2012) ', 'https://www.themoviedb.org/t/p/original/xs1BRXnY5kStzwdxyrl2HYJOJCq.jpg');
    INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, ' Digimon Digital Monsters (1999) ','https://www.themoviedb.org/t/p/original/mUhLvUY0ndhxWr1xmDp6bZgddUZ.jpg');

INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 3, 4.0);